services:
    wardell_route_resolver.twig.extension:
        class: Wardell\RouteResolverBundle\Twig\Extension\RouteResolverExtension
        arguments: ["@router", "@security.context","%wardell_route_resolver_parameters%"]
        tags:
            - { name: twig.extension }
